trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'armsvc-calcapp'
  resourceGroupName: 'rg-calc-test'

stages:
- stage: DeployInfrastructure
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName) --location 'Japan East'
          az deployment group create --resource-group $(resourceGroupName) --template-file infrastructure/main.bicep
    displayName: 'Deploy Infrastructure'